[package]
name = "webxr"
version = "0.0.1"
authors = ["The Servo Project Developers"]
edition = "2018"

homepage = "https://github.com/servo/webxr"
repository = "https://github.com/servo/webxr"
keywords = ["webxr", "openvr", "oculus", "magicleap", "headset", "vr", "ar"]
license = "MPL-2.0"

description = '''A safe Rust API that provides a way to interact with
Virtual Reality and Augmented Reality devices and integration with
vendor-specific APIs like OpenVR, Oculus, GoogleVR and Magic Leap. The
API is inspired by the WebXR Device API (https://www.w3.org/TR/webxr/)
but adapted to Rust design patterns.'''

[lib]
path = "lib.rs"

[features]
glwindow = ["glutin"]
headless = []
hololens = []
ipc = ["webxr-api/ipc"]

[dependencies]
webxr-api = { path = "../webxr-api" }
euclid = "0.20"
gleam = "0.6"
glutin = { version = "0.21", optional = true }
log = "0.4"
